### PR TITLE
Fix invalid move bug

### LINKED ISSUE #55: Fix Invalid Move feature
Two colour-like diagonal stones must SHARE a colour-like orthogonal stone for the move to be valid

### PR DESCRIPTION
**Pull request by eferos93**
Fixed invalid move bug #55. 
Substituted the two functions for checking the _existence_ of orthogonal and diagonal intersections with two functions that _return_ respectively the orthogonal and diagonal, colour alike, intersections.

Two tests were added; @demirbilek95 could check them and see if you can refactor them with `DynamicTests` or other?

### CODE REVIEW

File: src/main/java/quentin/core/Board.java [hunk 1]
```diff
@@ -45,18 +46,18 @@ protected boolean isOccupied(Position position) throws OutsideOfBoardException {
...
     }
 
-    protected boolean existsDiagonallyAdjacentWithStone(Intersection intersection, Stone stone) {
+    protected Set<Intersection> getOrthogonallyAdjacentIntersectionsOfColour(Intersection intersection, Stone color) {
         return intersections.stream()
-                .anyMatch(otherIntersection ->
-                        otherIntersection.isDiagonalTo(intersection) && otherIntersection.hasStone(stone)
-                );
+                .filter(intersection::isOrthogonalTo)
+                .filter(diagonalIntersection -> diagonalIntersection.hasStone(color))
```
Comment (wilsonjefferson) [inline src/main/java/quentin/core/Board.java]: change from `diagonalIntersection` to `orthogonalIntersection`.

Comment (wilsonjefferson) [reply src/main/java/quentin/core/Board.java]: FIXED

**Review by wilsonjefferson — APPROVED** [review]

**Review by eferos93 — COMMENTED** [review]
All ok

**Review by demirbilek95 — APPROVED** [review]
